version: '3.8'

services:

  nginx:
    image: nginx:lts
    container_name: nginx

    build:
      context: ./nginx/
      args:
        - LOGIN

    restart: on-failure

    networks:
      - inception

    ports:
      - 443:443

    volumes:
      - wordpress_volume:/var/www/html

    depends_on:
      - wordpress

  wordpress:

    image: wordpress:lts
    container_name: wordpress

    # env_file:
    #   - .env

    build:
      context: ./wordpress/

    environment:
      - DOMAIN
      - WP_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
      - WP_DATABASE
      - WP_USER
      - WP_USER_PASS
      - WP_USER_EMAIL

    volumes:
      - wordpress_volume:/var/www/html

    networks:
      - inception

    expose:
      - 9000

    depends_on:
      - mariadb

  mariadb:
    image: mariadb:lts
    container_name: mariadb

    build:
      context: ./mariadb/
      args:
        - WP_DATABASE
        - WP_ADMIN_USER
        - WP_ADMIN_PASS

    expose:
      - 3306

    networks:
      - inception

    volumes:
      - mariadb_volume:/var/lib/mysql

volumes:
  mariadb_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/mariadb
    
  wordpress_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/wordpress

networks:
  inception:
    name: inception_network
    driver: bridge
